/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef ATMFORUM_H
#define ATMFORUM_H

#include "atmForumHelper.h"
/*
 * function declarations 
 */
void            init_atmForum(void);
#ifdef DO_ATMFAAL1PROFILETABLE
void            initialize_table_atmfAAL1ProfileTable(void);
Netsnmp_Node_Handler atmfAAL1ProfileTable_handler;
Netsnmp_First_Data_Point atmfAAL1ProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAAL1ProfileTable_get_next_data_point;

#endif                          /* DO_atmfAAL1ProfileTable.uc */
#ifdef DO_ATMFAAL2LESPROFILETABLE
void            initialize_table_atmfAAL2LESProfileTable(void);
Netsnmp_Node_Handler atmfAAL2LESProfileTable_handler;
Netsnmp_First_Data_Point atmfAAL2LESProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAAL2LESProfileTable_get_next_data_point;

#endif                          /* DO_atmfAAL2LESProfileTable.uc */
#ifdef DO_ATMFATMSERVICETYPETABLE
void            initialize_table_atmfAtmServiceTypeTable(void);
Netsnmp_Node_Handler atmfAtmServiceTypeTable_handler;
Netsnmp_First_Data_Point atmfAtmServiceTypeTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAtmServiceTypeTable_get_next_data_point;

#endif                          /* DO_atmfAtmServiceTypeTable.uc */
#ifdef DO_ATMFVPCABRTABLE
void            initialize_table_atmfVpcAbrTable(void);
Netsnmp_Node_Handler atmfVpcAbrTable_handler;
Netsnmp_First_Data_Point atmfVpcAbrTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfVpcAbrTable_get_next_data_point;

#endif                          /* DO_atmfVpcAbrTable.uc */
#ifdef DO_ATMFAAL2TRUNKINGPROFILETABLE
void            initialize_table_atmfAAL2TrunkingProfileTable(void);
Netsnmp_Node_Handler atmfAAL2TrunkingProfileTable_handler;
Netsnmp_First_Data_Point atmfAAL2TrunkingProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAAL2TrunkingProfileTable_get_next_data_point;

#endif                          /* DO_atmfAAL2TrunkingProfileTable.uc */
#ifdef DO_ATMFATMSERVICECONNINFOTABLE
void            initialize_table_atmfAtmServiceConnInfoTable(void);
Netsnmp_Node_Handler atmfAtmServiceConnInfoTable_handler;
Netsnmp_First_Data_Point atmfAtmServiceConnInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAtmServiceConnInfoTable_get_next_data_point;

#endif                          /* DO_atmfAtmServiceConnInfoTable.uc */
#ifdef DO_ATMFNETPREFIXTABLE
void            initialize_table_atmfNetPrefixTable(void);
Netsnmp_Node_Handler atmfNetPrefixTable_handler;
Netsnmp_First_Data_Point atmfNetPrefixTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfNetPrefixTable_get_next_data_point;

#endif                          /* DO_atmfNetPrefixTable.uc */
#ifdef DO_ATMFVCCABRTABLE
void            initialize_table_atmfVccAbrTable(void);
Netsnmp_Node_Handler atmfVccAbrTable_handler;
Netsnmp_First_Data_Point atmfVccAbrTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfVccAbrTable_get_next_data_point;

#endif                          /* DO_atmfVccAbrTable.uc */
#ifdef DO_ATMFAAL5PROFILETABLE
void            initialize_table_atmfAAL5ProfileTable(void);
Netsnmp_Node_Handler atmfAAL5ProfileTable_handler;
Netsnmp_First_Data_Point atmfAAL5ProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAAL5ProfileTable_get_next_data_point;

#endif                          /* DO_atmfAAL5ProfileTable.uc */
#ifdef DO_ATMFATMSERVICECONNINFOEXTENSIONTABLE
void           
initialize_table_atmfAtmServiceConnInfoExtensionTable(void);
Netsnmp_Node_Handler atmfAtmServiceConnInfoExtensionTable_handler;
Netsnmp_First_Data_Point
    atmfAtmServiceConnInfoExtensionTable_get_first_data_point;
Netsnmp_Next_Data_Point
    atmfAtmServiceConnInfoExtensionTable_get_next_data_point;

#endif                          /* DO_atmfAtmServiceConnInfoExtensionTable.uc */
#ifdef DO_ATMFAAL34PROFILETABLE
void            initialize_table_atmfAAL34ProfileTable(void);
Netsnmp_Node_Handler atmfAAL34ProfileTable_handler;
Netsnmp_First_Data_Point atmfAAL34ProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAAL34ProfileTable_get_next_data_point;

#endif                          /* DO_atmfAAL34ProfileTable.uc */
#ifdef DO_ATMFSRVCREGTABLE
void            initialize_table_atmfSrvcRegTable(void);
Netsnmp_Node_Handler atmfSrvcRegTable_handler;
Netsnmp_First_Data_Point atmfSrvcRegTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfSrvcRegTable_get_next_data_point;

#endif                          /* DO_atmfSrvcRegTable.uc */
#ifdef DO_ATMFADDRESSREGISTRATIONADMINTABLE
void            initialize_table_atmfAddressRegistrationAdminTable(void);
Netsnmp_Node_Handler atmfAddressRegistrationAdminTable_handler;
Netsnmp_First_Data_Point
    atmfAddressRegistrationAdminTable_get_first_data_point;
Netsnmp_Next_Data_Point
    atmfAddressRegistrationAdminTable_get_next_data_point;

#endif                          /* DO_atmfAddressRegistrationAdminTable.uc */
#ifdef DO_ATMFATMSTATSTABLE
void            initialize_table_atmfAtmStatsTable(void);
Netsnmp_Node_Handler atmfAtmStatsTable_handler;
Netsnmp_First_Data_Point atmfAtmStatsTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAtmStatsTable_get_next_data_point;

#endif                          /* DO_atmfAtmStatsTable.uc */
#ifdef DO_ATMFAAL5PROFILEEXTENSIONTABLE
void            initialize_table_atmfAAL5ProfileExtensionTable(void);
Netsnmp_Node_Handler atmfAAL5ProfileExtensionTable_handler;
Netsnmp_First_Data_Point
    atmfAAL5ProfileExtensionTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAAL5ProfileExtensionTable_get_next_data_point;

#endif                          /* DO_atmfAAL5ProfileExtensionTable.uc */
#ifdef DO_ATMFAAL2COMMONPROFILETABLE
void            initialize_table_atmfAAL2CommonProfileTable(void);
Netsnmp_Node_Handler atmfAAL2CommonProfileTable_handler;
Netsnmp_First_Data_Point atmfAAL2CommonProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAAL2CommonProfileTable_get_next_data_point;

#endif                          /* DO_atmfAAL2CommonProfileTable.uc */
#ifdef DO_ATMFVPCTABLE
void            initialize_table_atmfVpcTable(void);
Netsnmp_Node_Handler atmfVpcTable_handler;
Netsnmp_First_Data_Point atmfVpcTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfVpcTable_get_next_data_point;

#endif                          /* DO_atmfVpcTable.uc */
#ifdef DO_ATMFATMLAYERTABLE
void            initialize_table_atmfAtmLayerTable(void);
Netsnmp_Node_Handler atmfAtmLayerTable_handler;
Netsnmp_First_Data_Point atmfAtmLayerTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAtmLayerTable_get_next_data_point;

#endif                          /* DO_atmfAtmLayerTable.uc */
#ifdef DO_ATMFADDRESSTABLE
void            initialize_table_atmfAddressTable(void);
Netsnmp_Node_Handler atmfAddressTable_handler;
Netsnmp_First_Data_Point atmfAddressTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfAddressTable_get_next_data_point;

#endif                          /* DO_atmfAddressTable.uc */
#ifdef DO_ATMFPORTTABLE
void            initialize_table_atmfPortTable(void);
Netsnmp_Node_Handler atmfPortTable_handler;
Netsnmp_First_Data_Point atmfPortTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfPortTable_get_next_data_point;

#endif                          /* DO_atmfPortTable.uc */
#ifdef DO_ATMFVCCTABLE
void            initialize_table_atmfVccTable(void);
Netsnmp_Node_Handler atmfVccTable_handler;
Netsnmp_First_Data_Point atmfVccTable_get_first_data_point;
Netsnmp_Next_Data_Point atmfVccTable_get_next_data_point;

#endif                          /* DO_atmfVccTable.uc */
#ifdef DO_ATMFATMSERVICETYPEEXTENSIONTABLE
void            initialize_table_atmfAtmServiceTypeExtensionTable(void);
Netsnmp_Node_Handler atmfAtmServiceTypeExtensionTable_handler;
Netsnmp_First_Data_Point
    atmfAtmServiceTypeExtensionTable_get_first_data_point;
Netsnmp_Next_Data_Point
    atmfAtmServiceTypeExtensionTable_get_next_data_point;

#endif                          /* DO_atmfAtmServiceTypeExtensionTable.uc */

void init_atmfMySystemIdentifier(void);

/*
 * column number definitions for table atmfAAL1ProfileTable 
 */
#define COLUMN_ATMFAAL1PROFILEINDEX		1
#define COLUMN_ATMFAAL1SUBTYPE		2
#define COLUMN_ATMFAAL1CBRRATE		3
#define COLUMN_ATMFAAL1CLKRECOVERYTYPE		4
#define COLUMN_ATMFAAL1FEC		5
#define COLUMN_ATMFAAL1SDT		6
#define COLUMN_ATMFAAL1PARTIALLYFILLEDCELLS		7
#define COLUMN_ATMFAAL1CELLLOSSINTEGRPERIOD		8

/*
 * column number definitions for table atmfAAL2LESProfileTable 
 */
#define COLUMN_ATMFAAL2CPSCIDLOWERLIMIT		1
#define COLUMN_ATMFAAL2CPSCIDUPPERLIMIT		2
#define COLUMN_ATMFAAL2CPSOPTIMISATION		3

/*
 * column number definitions for table atmfAtmServiceTypeTable 
 */
#define COLUMN_ATMFATMSERVICETYPEINDEX		1
#define COLUMN_ATMFATMSERVICEPROVIDERNAME		2
#define COLUMN_ATMFATMSERVICENAME		3
#define COLUMN_ATMFATMSERVICESUBNAME		4
#define COLUMN_ATMFATMSERVICECLIENT		5
#define COLUMN_ATMFATMSERVICETMCATEGORY		6
#define COLUMN_ATMFATMSERVICETMCONFORMANCEDEF		7

/*
 * column number definitions for table atmfVpcAbrTable 
 */
#define COLUMN_ATMFVPCABRPORTINDEX		1
#define COLUMN_ATMFVPCABRVPI		2
#define COLUMN_ATMFVPCABRTRANSMITICR		3
#define COLUMN_ATMFVPCABRTRANSMITNRM		4
#define COLUMN_ATMFVPCABRTRANSMITTRM		5
#define COLUMN_ATMFVPCABRTRANSMITCDF		6
#define COLUMN_ATMFVPCABRTRANSMITRIF		7
#define COLUMN_ATMFVPCABRTRANSMITRDF		8
#define COLUMN_ATMFVPCABRTRANSMITADTF		9
#define COLUMN_ATMFVPCABRTRANSMITCRM		10

/*
 * column number definitions for table atmfAAL2TrunkingProfileTable 
 */
#define COLUMN_ATMFAAL2VCCI		1
#define COLUMN_ATMFAAL2SIGNALINGVCCI		2

/*
 * column number definitions for table atmfAtmServiceConnInfoTable 
 */
#define COLUMN_ATMFATMSERVICEPORTINDEX		1
#define COLUMN_ATMFATMSERVICEVPI		2
#define COLUMN_ATMFATMSERVICEVCI		3
#define COLUMN_ATMFATMSERVICESIGNALID		4
#define COLUMN_ATMFATMSERVICECONNSERVICEINDEX		5
#define COLUMN_ATMFATMSERVICECONNNAME		6
#define COLUMN_ATMFATMSERVICECONNAALTYPE		7
#define COLUMN_ATMFATMSERVICECONNAALINDEX		8

/*
 * column number definitions for table atmfNetPrefixTable 
 */
#define COLUMN_ATMFNETPREFIXPORT		1
#define COLUMN_ATMFNETPREFIXPREFIX		2
#define COLUMN_ATMFNETPREFIXSTATUS		3

/*
 * column number definitions for table atmfVccAbrTable 
 */
#define COLUMN_ATMFVCCABRPORTINDEX		1
#define COLUMN_ATMFVCCABRVPI		2
#define COLUMN_ATMFVCCABRVCI		3
#define COLUMN_ATMFVCCABRTRANSMITICR		4
#define COLUMN_ATMFVCCABRTRANSMITNRM		5
#define COLUMN_ATMFVCCABRTRANSMITTRM		6
#define COLUMN_ATMFVCCABRTRANSMITCDF		7
#define COLUMN_ATMFVCCABRTRANSMITRIF		8
#define COLUMN_ATMFVCCABRTRANSMITRDF		9
#define COLUMN_ATMFVCCABRTRANSMITADTF		10
#define COLUMN_ATMFVCCABRTRANSMITCRM		11

/*
 * column number definitions for table atmfAAL5ProfileTable 
 */
#define COLUMN_ATMFAAL5PROFILEINDEX		1
#define COLUMN_ATMFAAL5MAXCPCSSDUSIZEFORWARD		2
#define COLUMN_ATMFAAL5MAXCPCSSDUSIZEBACKWARD		3
#define COLUMN_ATMFAAL5AALMODE		4
#define COLUMN_ATMFAAL5SSCSTYPE		5

/*
 * column number definitions for table atmfAtmServiceConnInfoExtensionTable 
 */
#define COLUMN_ATMFATMSERVICEPHYMACIDENTIFIER		1

/*
 * column number definitions for table atmfAAL34ProfileTable 
 */
#define COLUMN_ATMFAAL34PROFILEINDEX		1
#define COLUMN_ATMFAAL34MAXCPCSSDUSIZEFORWARD		2
#define COLUMN_ATMFAAL34MAXCPCSSDUSIZEBACKWARD		3
#define COLUMN_ATMFAAL34MIDRANGELOW		4
#define COLUMN_ATMFAAL34MIDRANGEHIGH		5
#define COLUMN_ATMFAAL34AALMODE		6
#define COLUMN_ATMFAAL34SSCSTYPE		7

/*
 * column number definitions for table atmfSrvcRegTable 
 */
#define COLUMN_ATMFSRVCREGPORT		1
#define COLUMN_ATMFSRVCREGSERVICEID		2
#define COLUMN_ATMFSRVCREGATMADDRESS		3
#define COLUMN_ATMFSRVCREGADDRESSINDEX		4
#define COLUMN_ATMFSRVCREGPARM1		5

/*
 * column number definitions for table atmfAddressRegistrationAdminTable 
 */
#define COLUMN_ATMFADDRESSREGISTRATIONADMININDEX		1
#define COLUMN_ATMFADDRESSREGISTRATIONADMINSTATUS		2

/*
 * column number definitions for table atmfAtmStatsTable 
 */
#define COLUMN_ATMFATMSTATSINDEX		1
#define COLUMN_ATMFATMSTATSRECEIVEDCELLS		2
#define COLUMN_ATMFATMSTATSDROPPEDRECEIVEDCELLS		3
#define COLUMN_ATMFATMSTATSTRANSMITTEDCELLS		4

/*
 * column number definitions for table atmfAAL5ProfileExtensionTable 
 */
#define COLUMN_ATMFAAL5VCCI		1

/*
 * column number definitions for table atmfAAL2CommonProfileTable 
 */
#define COLUMN_ATMFAAL2PROFILEINDEX		1
#define COLUMN_ATMFAAL2APPLICATIONIDENTIFIER		2
#define COLUMN_ATMFAAL2CONFIGRESPONSIBILITY		3
#define COLUMN_ATMFAAL2CPSMAXMULTIPLEXEDCHANNELS		4
#define COLUMN_ATMFAAL2CPSMAXSDULENGTH		5
#define COLUMN_ATMFAAL2SSCSMAXSSSARSDULENGTH		6
#define COLUMN_ATMFAAL2SSCSSSTEDSTATUS		7
#define COLUMN_ATMFAAL2SSCSSSADTSTATUS		8
#define COLUMN_ATMFAAL2SSCSSERVICECATEGORY		9
#define COLUMN_ATMFAAL2SSCSAUDIOSERVICETRANSPORT		10
#define COLUMN_ATMFAAL2SSCSPROFILESOURCE		11
#define COLUMN_ATMFAAL2SSCSIEEEOUI		12
#define COLUMN_ATMFAAL2SSCSPREDEFINEDPROFILEIDENTIFIER		13
#define COLUMN_ATMFAAL2SSCSPCMENCODING		14
#define COLUMN_ATMFAAL2SSCSFAXDEMODULATIONTRANSPORT		15
#define COLUMN_ATMFAAL2SSCSCASSIGNALINGTRANSPORT		16
#define COLUMN_ATMFAAL2SSCSDTMFDIGITPACKETTRANSPORT		17
#define COLUMN_ATMFAAL2SSCSMFR1DIGITPACKETTRANSPORT		18
#define COLUMN_ATMFAAL2SSCSMFR2DIGITPACKETTRANSPORT		19
#define COLUMN_ATMFAAL2SSCSCIRCUITMODEDATATRANSPORT		20
#define COLUMN_ATMFAAL2SSCSCIRCUITMODEDATANUMCHANNELS		21
#define COLUMN_ATMFAAL2SSCSFRAMEMODEDATATRANSPORT		22
#define COLUMN_ATMFAAL2SSCSFRAMEMODEDATAMAXLENGTH		23
#define COLUMN_ATMFAAL2SSCOPSDULENGTH		24
#define COLUMN_ATMFAAL2SSCOPUUFIELDLENGTH		25

/*
 * column number definitions for table atmfVpcTable 
 */
#define COLUMN_ATMFVPCPORTINDEX		1
#define COLUMN_ATMFVPCVPI		2
#define COLUMN_ATMFVPCOPERSTATUS		3
#define COLUMN_ATMFVPCTRANSMITTRAFFICDESCRIPTORTYPE		4
#define COLUMN_ATMFVPCTRANSMITTRAFFICDESCRIPTORPARAM1		5
#define COLUMN_ATMFVPCTRANSMITTRAFFICDESCRIPTORPARAM2		6
#define COLUMN_ATMFVPCTRANSMITTRAFFICDESCRIPTORPARAM3		7
#define COLUMN_ATMFVPCTRANSMITTRAFFICDESCRIPTORPARAM4		8
#define COLUMN_ATMFVPCTRANSMITTRAFFICDESCRIPTORPARAM5		9
#define COLUMN_ATMFVPCRECEIVETRAFFICDESCRIPTORTYPE		10
#define COLUMN_ATMFVPCRECEIVETRAFFICDESCRIPTORPARAM1		11
#define COLUMN_ATMFVPCRECEIVETRAFFICDESCRIPTORPARAM2		12
#define COLUMN_ATMFVPCRECEIVETRAFFICDESCRIPTORPARAM3		13
#define COLUMN_ATMFVPCRECEIVETRAFFICDESCRIPTORPARAM4		14
#define COLUMN_ATMFVPCRECEIVETRAFFICDESCRIPTORPARAM5		15
#define COLUMN_ATMFVPCQOSCATEGORY		16
#define COLUMN_ATMFVPCTRANSMITQOSCLASS		17
#define COLUMN_ATMFVPCRECEIVEQOSCLASS		18
#define COLUMN_ATMFVPCBESTEFFORTINDICATOR		19
#define COLUMN_ATMFVPCSERVICECATEGORY		20

/*
 * column number definitions for table atmfAtmLayerTable 
 */
#define COLUMN_ATMFATMLAYERINDEX		1
#define COLUMN_ATMFATMLAYERMAXVPCS		2
#define COLUMN_ATMFATMLAYERMAXVCCS		3
#define COLUMN_ATMFATMLAYERCONFIGUREDVPCS		4
#define COLUMN_ATMFATMLAYERCONFIGUREDVCCS		5
#define COLUMN_ATMFATMLAYERMAXVPIBITS		6
#define COLUMN_ATMFATMLAYERMAXVCIBITS		7
#define COLUMN_ATMFATMLAYERUNITYPE		8
#define COLUMN_ATMFATMLAYERUNIVERSION		9
#define COLUMN_ATMFATMLAYERDEVICETYPE		10
#define COLUMN_ATMFATMLAYERILMIVERSION		11
#define COLUMN_ATMFATMLAYERNNISIGVERSION		12
#define COLUMN_ATMFATMLAYERMAXSVPCVPI		13
#define COLUMN_ATMFATMLAYERMAXSVCCVPI		14
#define COLUMN_ATMFATMLAYERMINSVCCVCI		15

/*
 * column number definitions for table atmfAddressTable 
 */
#define COLUMN_ATMFADDRESSPORT		1
#define COLUMN_ATMFADDRESSATMADDRESS		2
#define COLUMN_ATMFADDRESSSTATUS		3
#define COLUMN_ATMFADDRESSORGSCOPE		4

/*
 * column number definitions for table atmfPortTable 
 */
#define COLUMN_ATMFPORTINDEX		1
#define COLUMN_ATMFPORTADDRESS		2
#define COLUMN_ATMFPORTTRANSMISSIONTYPE		3
#define COLUMN_ATMFPORTMEDIATYPE		4
#define COLUMN_ATMFPORTOPERSTATUS		5
#define COLUMN_ATMFPORTSPECIFIC		6
#define COLUMN_ATMFPORTMYIFNAME		7
#define COLUMN_ATMFPORTMYIFIDENTIFIER		8

/*
 * column number definitions for table atmfVccTable 
 */
#define COLUMN_ATMFVCCPORTINDEX		1
#define COLUMN_ATMFVCCVPI		2
#define COLUMN_ATMFVCCVCI		3
#define COLUMN_ATMFVCCOPERSTATUS		4
#define COLUMN_ATMFVCCTRANSMITTRAFFICDESCRIPTORTYPE		5
#define COLUMN_ATMFVCCTRANSMITTRAFFICDESCRIPTORPARAM1		6
#define COLUMN_ATMFVCCTRANSMITTRAFFICDESCRIPTORPARAM2		7
#define COLUMN_ATMFVCCTRANSMITTRAFFICDESCRIPTORPARAM3		8
#define COLUMN_ATMFVCCTRANSMITTRAFFICDESCRIPTORPARAM4		9
#define COLUMN_ATMFVCCTRANSMITTRAFFICDESCRIPTORPARAM5		10
#define COLUMN_ATMFVCCRECEIVETRAFFICDESCRIPTORTYPE		11
#define COLUMN_ATMFVCCRECEIVETRAFFICDESCRIPTORPARAM1		12
#define COLUMN_ATMFVCCRECEIVETRAFFICDESCRIPTORPARAM2		13
#define COLUMN_ATMFVCCRECEIVETRAFFICDESCRIPTORPARAM3		14
#define COLUMN_ATMFVCCRECEIVETRAFFICDESCRIPTORPARAM4		15
#define COLUMN_ATMFVCCRECEIVETRAFFICDESCRIPTORPARAM5		16
#define COLUMN_ATMFVCCQOSCATEGORY		17
#define COLUMN_ATMFVCCTRANSMITQOSCLASS		18
#define COLUMN_ATMFVCCRECEIVEQOSCLASS		19
#define COLUMN_ATMFVCCBESTEFFORTINDICATOR		20
#define COLUMN_ATMFVCCTRANSMITFRAMEDISCARD		21
#define COLUMN_ATMFVCCRECEIVEFRAMEDISCARD		22
#define COLUMN_ATMFVCCSERVICECATEGORY		23

/*
 * column number definitions for table atmfAtmServiceTypeExtensionTable 
 */
#define COLUMN_ATMFATMSERVICELAYER2PROTOCOLID		1
#define COLUMN_ATMFATMSERVICELAYER3PROTOCOLID		2
#endif                          /* ATMFORUM_H */
