#!/bin/sh

vid="$1"
mac="$2"
flags="$3"

cd /proc
echo "05 02 06:" "$mac" > switch
echo "05 08 02:" "$vid" > switch

echo "05 00 01: 81" > switch
sleep 1

if [ "$#" -gt  2 ]; then
  echo "05 18 02:" "$flags" > switch
  echo "05 00 01: 80" > switch
  sleep 1
fi

echo "05 18 02" > switch
echo "$vid:$mac: flags -> `cat switch`"



