/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("atmMIB")) init_atmMIB();
  if (should_init("system_mib")) init_system_mib();
  if (should_init("sysORTable")) init_sysORTable();
  if (should_init("at")) init_at();
  if (should_init("interfaces")) init_interfaces();
  if (should_init("snmp_mib")) init_snmp_mib();
  if (should_init("tcp")) init_tcp();
  if (should_init("icmp")) init_icmp();
  if (should_init("ip")) init_ip();
  if (should_init("udp")) init_udp();
  if (should_init("vacm_vars")) init_vacm_vars();
#ifdef BRCM_SNMP_MIB_SUPPORT
  if (should_init("setSerialNo")) init_setSerialNo();
  if (should_init("snmpNotifyTable")) init_snmpNotifyTable();
  if (should_init("snmpNotifyFilterTable")) init_snmpNotifyFilterTable();
  if (should_init("snmpNotifyFilterProfileTable")) init_snmpNotifyFilterProfileTable();
#endif /* BRCM_SNMP_MIB_SUPPORT */
#ifdef BRCM_SNMP_WRITE_SUPPORT
  if (should_init("override")) init_override();
#endif /* BRCM_SNMP_WRITE_SUPPORT */
  if (should_init("var_route")) init_var_route();
#ifdef BRCM_SNMP_MIB_SUPPORT
  if (should_init("vacm_context")) init_vacm_context();
#endif /* BRCM_SNMP_MIB_SUPPORT */

  if (should_init("adsl_mib")) init_adsl_mib();
  if (should_init("atmForum")) init_atmForum();
