#!/bin/bash

ROOTFS=$PROFILE/fs

# Create FIFO devices
mknod $ROOTFS/dev/initctl p

#Create character devices
mknod $ROOTFS/dev/mem c 1 1
mknod $ROOTFS/dev/kmem c 1 2
mknod $ROOTFS/dev/null c 1 3
mknod $ROOTFS/dev/port c 1 4
mknod $ROOTFS/dev/zero c 1 5
mknod $ROOTFS/dev/ptyp0 c 2 0
mknod $ROOTFS/dev/ptyp1 c 2 1
mknod $ROOTFS/dev/ttyp0 c 3 0
mknod $ROOTFS/dev/ttyp1 c 3 1
mknod $ROOTFS/dev/tty0 c 4 0
mknod $ROOTFS/dev/tty1 c 4 1
mknod $ROOTFS/dev/ttyS0 c 4 64
mknod $ROOTFS/dev/tty c 5 0
mknod $ROOTFS/dev/console c 5 1
mknod $ROOTFS/dev/ptmx c 5 2
mknod $ROOTFS/dev/ppp c 108 0
mknod $ROOTFS/dev/printer0 c 180 0
mknod $ROOTFS/dev/urandom c 1 9

# Create Broadcom specific devices
mknod $ROOTFS/dev/bcmatm0 c 205 0
mknod $ROOTFS/dev/brcmboard c 206 0
mknod $ROOTFS/dev/bcmvdsl0 c 207 0
mknod $ROOTFS/dev/bcmadsl0 c 208 0
mknod $ROOTFS/dev/bcmendpoint0 c 209 0
mknod $ROOTFS/dev/bcmaal20 c 210 0
mknod $ROOTFS/dev/bcmles0 c 211 0
mknod $ROOTFS/dev/bcm c 212 0
mknod $ROOTFS/dev/ac97 c 222 0
mknod $ROOTFS/dev/slac c 223 0
mknod $ROOTFS/dev/bcmprof c 224 0
mknod $ROOTFS/dev/si3215 c 225 0
mknod $ROOTFS/dev/bcmatmb0 c 226 0
mknod $ROOTFS/dev/p8021ag0 c 227 0
mknod $ROOTFS/dev/bcmxtmcfg0 c 228 0

# Create block devices
mknod $ROOTFS/dev/ram0 b 1 0
mknod $ROOTFS/dev/ram1 b 1 1
mknod $ROOTFS/dev/ram2 b 1 2
mknod $ROOTFS/dev/ram3 b 1 3
ln -s ram1 $ROOTFS/dev/ram

mknod $ROOTFS/dev/mtdblock0 b 31 0
mknod $ROOTFS/dev/mtdblock1 b 31 1
mknod $ROOTFS/dev/mtdblock2 b 31 2
mknod $ROOTFS/dev/mtdblock3 b 31 3
mknod $ROOTFS/dev/mtdblock4 b 31 4
mknod $ROOTFS/dev/mtdblock5 b 31 5
mknod $ROOTFS/dev/mtdblock6 b 31 6
mknod $ROOTFS/dev/mtdblock7 b 31 7
